### PR TITLE
Feature/118 redesign actor interface

### LINKED ISSUE #118: Redesign actor interface
Design
- DssActor interface
- AbstractDssActor abstract class
- DssMasterActor interface
- DssServiceActor interface

### PR DESCRIPTION
**Pull request by ztkmkoo**
### motivation
I think akka actor design is too complex(?) and not intuitive.

### job
Design the main actors interface.
- DssActor
  - all the actors parent interface
- DssMasterActor
  - master actor 
  - root actor 
  - manage other actors
- DssNetworkActor
  - server binding actor
- DssResolverActor 
  - receive request from network actor and decide which service actor to send

### use case
image

```
@startuml
:Master: as Master <<Actor>>
Network <<Actor>>
Resolver <<Actor>>
Service <<Actor>>
Exception <<Actor>>
Client <<User>> #blue

Master --|> Network: listen
Network <- Client: req
Network --> Resolver: req
Resolver -> Service: req
Network <-- Service: res
Service -> Exception: exception
Network <-- Exception: res

Master . Network: child
Master . Resolver: child
Master . Service: child
Master . Exception: child
@enduml
```

### CODE REVIEW

**Comment by ztkmkoo** [comment]
Wow?
Sonarcloud bot is crazy.. push multiple results..

**Comment by Alencion** [comment]
It is good structure!!

It seems that each actor has a better meaning.

**Review by Alencion — APPROVED** [review]

**Review by RulLu16 — APPROVED** [review]
Oh, It's really good redesigning! These structure make it easier to understand dss projects than previous structure. 
Also, adding that image file of structure to Wiki will be good for understanding projects. :)

**Comment by RulLu16** [comment]
And I have a question. After this pr, is there any differences in other actors like DssRestMasterActor? I just wonder how these structure affect to other class.

**Comment by ztkmkoo** [comment]
> 
> 
> And I have a question. After this pr, is there any differences in other actors like DssRestMasterActor? I just wonder how these structure affect to other class.

Ultimately right.
But this feature will not directly merge to develop branch.
(Oh,, my mistake, it will be merged to develop-0.5 branch)

And we need to re-implement master actor with old DssRestMasterActor.
But you do not have worry bout that. the object dependencies in actor is not strong, we can easily re-implement with old one.

When all of the jobs done, we will merge develop-0.5 to develop and release new version.

**Comment by ztkmkoo** [comment]
I will close this pr.
It is my fault that create pr to develop branch. I will reopen new one.

**Pull request closed without merging**
