### PR TITLE
Feature/uml doc

### PR DESCRIPTION
**Pull request by ztkmkoo**
It is plantuml for dss server structure and sequence flow.
You can see the image in the wiki(https://github.com/ztkmkoo/dss/wiki/Project-Structure, Server initialize flow and Rest event handling flow)

### CODE REVIEW

**Comment by ztkmkoo** [comment]
> 
> 
> [Coverage Status](https://coveralls.io/builds/33088020)
> 
> Coverage decreased (-0.8%) to 83.192% when pulling **[7b1c03d](https://github.com/ztkmkoo/dss/commit/7b1c03d8f8ce9e5931cf626cfb2af0fdf78fee14) on feature/uml_doc** into **[4a8bbb0](https://github.com/ztkmkoo/dss/commit/4a8bbb09f6265b1df0713c2be83c7a07583cdc9c) on develop**.

Why??decreased... I cannot understand.

**Comment by Alencion** [comment]
> > [Coverage Status](https://coveralls.io/builds/33088020)
> > Coverage decreased (-0.8%) to 83.192% when pulling **[7b1c03d](https://github.com/ztkmkoo/dss/commit/7b1c03d8f8ce9e5931cf626cfb2af0fdf78fee14) on feature/uml_doc** into **[4a8bbb0](https://github.com/ztkmkoo/dss/commit/4a8bbb09f6265b1df0713c2be83c7a07583cdc9c) on develop**.
> 
> Why??decreased... I cannot understand.

I don't really know either.

But I guess, this branch's original coverage was 83.192% and the develop branch's coverage decreased 0.8% coverage by latest merged commit.

So, latest merged commit was applied to this branch with a 0.8% coverage reduction.

**Comment by ztkmkoo** [comment]
@Alencion 
Could you like to review this flow?

**Review by Doyuni — APPROVED** [review]
Server initialize flow is clear.
And..`Exception occured` part on Rest event handling flow seems to be correct, Is it right?

**Comment by ztkmkoo** [comment]
> 
> 
> Server initialize flow is clear.
> And..`Exception occured` part on Rest event handling flow seems to be correct, Is it right?

Hi~
`Exception occured` part is on #119 now (will be merged on this Thursday)

**Comment by ztkmkoo** [comment]
@Alencion 
I update my async flow in rest event handling.svg

**Comment by Alencion** [comment]
I found some docs.

old version.
http://wiki.4intra.net/images/c/c4/PlantUML_Language_Reference_Guide.pdf
latest version.
http://plantuml.com/en/guide

In old version, it expresses asynchronous with `->>` but latest version don't mention each arrow feature. 

So, how about to set the arrow feature?

**Comment by ztkmkoo** [comment]
> 
> 
> I found some docs.
> 
> old version.
> http://wiki.4intra.net/images/c/c4/PlantUML_Language_Reference_Guide.pdf
> latest version.
> http://plantuml.com/en/guide
> 
> In old version, it expresses asynchronous with `->>` but latest version don't mention each arrow feature.
> 
> So, how about to set the arrow feature?

Thank you.
Let's use `->>` for asynchronous  arrow feature

**Review by Alencion — APPROVED** [review]
LGTM

**Pull request merged**
