### PR TITLE
[#58] Add lombok.config file

### LINKED ISSUE #58: Add lombok.config files
Project lombok is very useful java library helps us automatically plugs into your editor and build tools.
https://projectlombok.org/

But, there are some known problems. (like @Data annotations, so dangerous sometimes)
Try to add an config to make it safe.

### PR DESCRIPTION
**Pull request by RulLu16**
Resolves #58 

add lombok.config file in project root directory.

### List of configurations
1. Error for data annotation
2. Error for AllArgsConstructor annotation
3. Error for RequiredArgsConstructor annotation
4. Warning for ToString annotation
5. Warning for EqualsAndHashCode annotation

### Edit

If you want another configuration, please use this format

`lombok.{annotation_Name}.flagUsage = [warning or error]`

### CODE REVIEW

**Comment by ztkmkoo** [comment]
https://projectlombok.org/features/configuration

**Comment by RulLu16** [comment]
@ztkmkoo 
I agree with your recommendations. 
So I add config.stopBubbling and add other ignore annotations.
- @value
- @val
- @nonnull
- @cleanup
- @SneakyThrows
- @synchronized

Also I recommend to add more ignore annotations.
- @var

Because  var functionality is available natively since Java 10, and after Java 10, lombok's var is not working successfully. 

About warnings, I added @EqualsAndHashCode warning because I thought 
indiscriminate use of @EqualsAndHashCode can cause problems in mutable class. 
Also added @ToString warning because it can cause StackOverflow with circular references. 

That warnings are just for avoiding indiscriminate use. So if you don't want, I remove them

**Comment by ztkmkoo** [comment]
> @ztkmkoo
> I agree with your recommendations.
> So I add config.stopBubbling and add other ignore annotations.
> 
> * @value
> * @Val
> * @nonnull
> * @cleanup
> * @SneakyThrows
> * @synchronized
> 
> Also I recommend to add more ignore annotations.
> 
> * @var
> 
> Because var functionality is available natively since Java 10, and after Java 10, lombok's var is not working successfully.
> 
> About warnings, I added @EqualsAndHashCode warning because I thought
> indiscriminate use of @EqualsAndHashCode can cause problems in mutable class.
> Also added @tostring warning because it can cause StackOverflow with circular references.
> 
> That warnings are just for avoiding indiscriminate use. So if you don't want, I remove them

Yap. I also think  @EqualsAndHashCode and @tostring cause problems.
What is the best practice for these annotation. warning or error? (I think you should not remove the configs.. at least warning. I just wonder why you set them warning not error..)

**Comment by RulLu16** [comment]
> Yap. I also think @EqualsAndHashCode and @tostring cause problems.
> What is the best practice for these annotation. warning or error? (I think you should not remove the configs.. at least warning. I just wonder why you set them warning not error..)

I misunderstand your first review. I thought you want @EqualsAndHashCode and @toString are not error or warning.. 

I just set them warning because I think that @EqualsAndHashCode and @toString are still useful and can be used in this project later. But to use @EqualsAndHashCode with no error, it should be used in immutable field in very limited way. 

So I suggest that make @EqualsAndHashCode be error, @toString be warning.

**Pull request merged**
